[package]
name = "server_2"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.140"
common = { path = "../common" }
sysinfo = "0.35.0"
nix = "0.30.1"
procfs = "0.17.0"
libc = "0.2.172"
